name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Fix next.config.js
        run: |
          if [ -f next.config.ts ]; then
            rm next.config.ts
          fi
          if [ ! -f next.config.js ]; then
            echo '/** @type {import("next").NextConfig} */
            const nextConfig = {
              output: "export",
              basePath: "/PortofolioIksvaku",
              assetPrefix: "/PortofolioIksvaku/",
              images: {
                unoptimized: true,
              },
              trailingSlash: true,
            };
            
            module.exports = nextConfig;' > next.config.js
          fi
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 